version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network
    volumes:
      - ./backend/src:/var/www
  mysql:
    image: mysql:8.3
    container_name: mysql_db
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: furusato
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app-network
  frontend:
   build:
     context: .
     dockerfile: ./frontend/Dockerfile
   volumes:
     - ./frontend/src:/app
   command: 'npm run dev'
   ports:
     - 3000:3000
   networks:
     - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./nginx/letsencrypt:/var/www/certbot
    depends_on:
      - frontend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/letsencrypt:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email $CERTBOT_EMAIL --agree-tos --no-eff-email --force-renewal -d furusatoknow.com

networks:
  app-network:
    driver: bridge
volumes:
  mysql-volume:


